In [ ]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

In [ ]:
cabecalhos = {'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 OPR/94.0.0.0 (Edition std-1)'}

requests.get('https://www.imdb.com/chart/moviemeter/?ref_=nv_mv_mpm', headers = cabecalhos)

resposta = requests.get('https://www.imdb.com/chart/moviemeter/?ref_=nv_mv_mpm')
desorganizado = resposta.text
resposta

In [ ]:
organizado = BeautifulSoup(desorganizado, "html.parser")

In [ ]:
filmes = organizado.find_all("td", {"class": "titleColumn"})
filmes_avaliacoes = organizado.find_all("td", {"class": "ratingColumn imdbRating"})

filmes_nome = []
filmes_data = []
filmes_nota = []

for filme in filmes:
  nome = filme.find("a").text
  data = filme.find("span").text.strip("()") 
  filmes_nome.append(nome)
  filmes_data.append(data)

 
for filme in filmes_avaliacoes:
  try:
    nota = filme.find("strong").text
    filmes_nota.append(nota)
  except AttributeError:
    filmes_nota.append("Sem nota")

In [ ]:
imdb = {"Filmes": filmes_nome,
       "Data de Lancamento": filmes_data,
       "Notas": filmes_nota}

filmes_populares = pd.DataFrame(imdb)
display(filmes_populares)

,Filmes,Data de Lancamento,Notas
0,Ant-Man and the Wasp: Quantumania,2023,6.6
1,The Flash,2023,Sem nota
2,Your Place or Mine,2023,5.6
3,Babylon,2022,7.3
4,Black Panther: Wakanda Forever,2022,6.8
...,...,...,...
95,Guillermo del Toro's Pinocchio,2022,7.6
96,The Lord of the Rings: The Fellowship of the Ring,2001,8.8
97,Avengers: Endgame,2019,8.4
98,"Alice, Darling",2022,5.4
99,Bones and All,2022,6.9

In [ ]:
display(filmes_populares.loc[filmes_populares["Filmes"] == "The Batman"])

In [ ]:
filmes_populares.to_csv("filmes_populares.csv", index=False)